import { Review, Testimonial } from './types';

export const reviews: Review[] = [
  // Reviews for Maji Motoni Retreat (Property 1)
  {
    id: 'rev-1',
    author: 'Emily Rodriguez',
    avatar: 'https://i.pravatar.cc/150?img=10',
    rating: 5,
    comment: 'Absolutely magical experience! The WiFi worked perfectly for my remote work, and watching elephants from the balcony during video calls was surreal. The staff went above and beyond, and the solar setup meant we never experienced power cuts. Worth every penny!',
    date: '2025-12-15',
    verified: true,
    propertyId: '1',
  },
  {
    id: 'rev-2',
    author: 'Michael Thompson',
    avatar: 'https://i.pravatar.cc/150?img=33',
    rating: 5,
    comment: 'This place exceeded all our expectations. The guides were incredibly knowledgeable, spotting animals we would have never seen on our own. The villa itself is eco-luxury at its finest – comfortable, modern, yet completely sustainable. Our kids (8 and 11) are still talking about it months later!',
    date: '2025-11-28',
    verified: true,
    propertyId: '1',
  },
  {
    id: 'rev-3',
    author: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/150?img=47',
    rating: 5,
    comment: 'As a photographer, the sunrise views from this property are unbeatable. The staff understood our early morning schedule and had coffee ready before our dawn drives. Internet was fast enough to upload RAW files. Simply outstanding!',
    date: '2025-10-10',
    verified: true,
    propertyId: '1',
  },

  // Reviews for Nairobi Sky Loft (Property 2)
  {
    id: 'rev-4',
    author: 'Alex Chen',
    avatar: 'https://i.pravatar.cc/150?img=12',
    rating: 5,
    comment: 'Perfect digital nomad setup. The 250Mbps WiFi is no joke – handled all my video calls and large file uploads without a hitch. Walking distance to great cafes and restaurants. The rooftop pool is a nice bonus after a long work day. Highly recommend for remote workers!',
    date: '2026-01-08',
    verified: true,
    propertyId: '2',
  },
  {
    id: 'rev-5',
    author: 'Jessica Martinez',
    avatar: 'https://i.pravatar.cc/150?img=26',
    rating: 5,
    comment: 'Stayed here for a month while working remotely. The natural light is incredible for content creation – I shot three brand campaigns from the apartment! The ring light and backdrop were thoughtful additions. Location is unbeatable. Will definitely return!',
    date: '2025-12-20',
    verified: true,
    propertyId: '2',
  },
  {
    id: 'rev-6',
    author: 'David Park',
    avatar: 'https://i.pravatar.cc/150?img=51',
    rating: 4,
    comment: 'Great place for business travelers. Super fast internet, comfortable workspace, and the gym is well-equipped. Only minor issue was occasional traffic noise, but earplugs solved that. The concierge was helpful arranging transportation. Would stay again.',
    date: '2025-11-15',
    verified: true,
    propertyId: '2',
  },

  // Reviews for Diani Azure Villa (Property 3)
  {
    id: 'rev-7',
    author: 'Sophie Anderson',
    avatar: 'https://i.pravatar.cc/150?img=44',
    rating: 5,
    comment: 'Dream beach vacation! The villa is even better than the photos. Chef Samuel prepared the most amazing seafood dishes. Kids loved the kayaks and the pool. Beach is literally 30 seconds away. Perfect for families who want luxury and beach access.',
    date: '2026-01-02',
    verified: true,
    propertyId: '3',
  },
  {
    id: 'rev-8',
    author: 'Thomas Mueller',
    avatar: 'https://i.pravatar.cc/150?img=14',
    rating: 5,
    comment: 'Honeymoon perfection! Private beach access meant we had our own slice of paradise. Sunsets from the rooftop terrace are unforgettable. The staff was discreet yet attentive. Couldn\'t have asked for a better romantic getaway.',
    date: '2025-12-18',
    verified: true,
    propertyId: '3',
  },

  // Reviews for Lamu Swahili House (Property 5)
  {
    id: 'rev-9',
    author: 'Rachel Green',
    avatar: 'https://i.pravatar.cc/150?img=48',
    rating: 5,
    comment: 'Stepping into this house is like traveling back in time. The architecture, the carved doors, the rooftop with ocean views – pure magic. Lamu is car-free which adds to the charm. The house manager Fatima was wonderful, sharing stories about the building\'s history. Unforgettable cultural experience!',
    date: '2025-12-05',
    verified: true,
    propertyId: '5',
  },
  {
    id: 'rev-10',
    author: 'James Wilson',
    avatar: 'https://i.pravatar.cc/150?img=52',
    rating: 5,
    comment: 'Best decision to stay in Old Town rather than a beach resort. This house has character and soul. Morning calls to prayer, dhows in the harbor, the smell of frankincense – it\'s an immersive cultural experience. WiFi was surprisingly good. Perfect for anyone who values authenticity over generic luxury.',
    date: '2025-11-20',
    verified: true,
    propertyId: '5',
  },

  // Reviews for Lake Naivasha Retreat (Property 9)
  {
    id: 'rev-11',
    author: 'Linda Watson',
    avatar: 'https://i.pravatar.cc/150?img=41',
    rating: 5,
    comment: 'Waking up to hippos on the lawn was surreal! The birdlife is incredible – we spotted over 100 species in three days. Perfect weekend escape from Nairobi. The boat safari at sunset was the highlight. Staff was knowledgeable about the wildlife. Highly recommend for nature lovers!',
    date: '2025-12-28',
    verified: true,
    propertyId: '9',
  },

  // Reviews for Karen Garden Villa (Property 8)
  {
    id: 'rev-12',
    author: 'Patricia Brown',
    avatar: 'https://i.pravatar.cc/150?img=49',
    rating: 5,
    comment: 'Relocated to Nairobi for work and this villa made the transition smooth. Spacious for our family of five, secure compound, excellent schools nearby. The garden is massive – kids play outside every day. Staff quarters were perfect for our nanny. Feels like home now!',
    date: '2025-11-10',
    verified: true,
    propertyId: '8',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    author: 'Emma L.',
    avatar: 'https://i.pravatar.cc/150?img=5',
    role: 'Content Creator',
    comment: 'The WiFi was fast enough for my Zoom calls! Uploaded 4K videos without issues. Plus, the natural lighting was perfect for my Instagram content. Safari Stays really understands what digital nomads need.',
    rating: 5,
    date: '2026-01-15',
    verified: true,
    propertyId: '2',
  },
  {
    id: 'test-2',
    author: 'David K.',
    avatar: 'https://i.pravatar.cc/150?img=33',
    role: 'Family Traveler',
    comment: 'Booking via WhatsApp was surprisingly smooth! The team answered all our questions instantly and even arranged airport pickup. Our kids loved the pool and seeing wildlife from the villa.',
    rating: 5,
    date: '2025-12-20',
    verified: true,
    propertyId: '1',
  },
  {
    id: 'test-3',
    author: 'Sarah M.',
    avatar: 'https://i.pravatar.cc/150?img=47',
    role: 'Photographer',
    comment: 'Found this gem through Safari Stays and it was perfect for my wildlife photography project. The guides knew exactly where to find the best shots. Will definitely use them again for my next Kenya trip!',
    rating: 5,
    date: '2025-11-28',
    verified: true,
    propertyId: '1',
  },
  {
    id: 'test-4',
    author: 'Michael R.',
    avatar: 'https://i.pravatar.cc/150?img=51',
    role: 'Business Traveler',
    comment: 'Needed a place in Nairobi for a month-long project. The Kilimani apartment was perfect – quiet, fast internet, and the daily housekeeping was a nice touch. Felt like a hotel but with the comfort of home.',
    rating: 5,
    date: '2025-12-10',
    verified: true,
    propertyId: '7',
  },
  {
    id: 'test-5',
    author: 'Lisa T.',
    avatar: 'https://i.pravatar.cc/150?img=44',
    role: 'Honeymoon Couple',
    comment: 'Our honeymoon at Diani was absolutely magical. The villa exceeded our expectations and the private beach access was everything we dreamed of. Thank you Safari Stays for making it perfect!',
    rating: 5,
    date: '2025-12-05',
    verified: true,
    propertyId: '3',
  },
  {
    id: 'test-6',
    author: 'James W.',
    avatar: 'https://i.pravatar.cc/150?img=14',
    role: 'Returning Guest',
    comment: 'This is my third stay with Safari Stays. The consistency in quality and the personal touch from the team keeps me coming back. They remember my preferences and make every stay special.',
    rating: 5,
    date: '2025-11-22',
    verified: true,
  },
  {
    id: 'test-7',
    author: 'Rachel G.',
    avatar: 'https://i.pravatar.cc/150?img=48',
    role: 'Solo Traveler',
    comment: 'As a solo female traveler, I felt completely safe. The properties are well-secured and the local team was always available if I needed anything. Safari Stays made my Kenya adventure worry-free!',
    rating: 5,
    date: '2025-11-15',
    verified: true,
    propertyId: '5',
  },
  {
    id: 'test-8',
    author: 'Tom H.',
    avatar: 'https://i.pravatar.cc/150?img=52',
    role: 'Digital Nomad',
    comment: 'Been working remotely from Nairobi for 3 months thanks to Safari Stays. The coworking recommendations were spot-on and the apartment WiFi never let me down. Living the dream here!',
    rating: 5,
    date: '2025-12-18',
    verified: true,
    propertyId: '2',
  },
];