import { Activity } from "./types";

// Comprehensive activities data for Diani, Watamu, and Malindi
export const activities: Activity[] = [
  // ============================================================================
  // DIANI BEACH ACTIVITIES
  // ============================================================================
  
  {
    id: 'act-001',
    slug: 'clear-kayak-photoshoot-diani',
    title: 'Clear Kayak Ocean Photoshoot',
    subtitle: 'Float above crystal waters while we capture your adventure',
    location: 'Diani Beach',
    region: 'diani',
    category: 'water-sports',
    type: 'photography',
    price: 14000, // $110 from pricing file
    currency: 'KES',
    duration: '1.5 hours',
    groupSize: { min: 1, max: 2 },
    difficulty: 'easy',
    featured: true,
    bestFor: ['Instagram Content', 'Couples', 'Solo Travelers', 'Content Creators'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200',
      alt: 'Clear Kayak Photoshoot',
      type: 'hero',
    },
    gallery: [],
    description: 'Experience the magic of floating on crystal-clear turquoise waters in a transparent kayak. This unique photoshoot combines adventure with stunning visuals, creating Instagram-worthy content that captures the essence of Diani\'s pristine coastline. Our professional photographers know exactly how to capture the perfect angle, making it look like you\'re floating on air.',
    highlights: [
      '10 professionally edited HD kayak photos',
      '1 cinematic Instagram Reel',
      'Shot in calm, clear water conditions',
      'Scenic offshore locations',
      'Professional photographer guide',
      'All equipment provided',
    ],
    included: [
      'Clear kayak rental',
      'Professional photography session',
      'HD photo editing (10 photos)',
      'Instagram Reel creation',
      'Life jacket and safety equipment',
      'Waterproof storage for belongings',
    ],
    notIncluded: [
      'Beach entry fee (if applicable)',
      'Additional printed photos',
      'Video footage beyond reel',
      'Transport to/from beach',
    ],
    itinerary: [
      { time: '09:00 AM', activity: 'Meet at Diani Beach access point' },
      { time: '09:15 AM', activity: 'Safety briefing and equipment fitting' },
      { time: '09:30 AM', activity: 'Paddle to photoshoot location' },
      { time: '09:45 AM', activity: 'Professional photoshoot session' },
      { time: '10:15 AM', activity: 'Return to shore and review shots' },
    ],
    meetingPoint: 'Diani Beach Main Access, near Forty Thieves Beach Bar',
    coordinates: { lat: -4.33, lng: 39.56 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '11:00 AM', '03:00 PM'],
      seasonalNotes: 'Best conditions October-March during calm seas',
    },
    whatToBring: [
      'Swimwear',
      'Sunscreen (reef-safe)',
      'Sunglasses with strap',
      'Towel',
      'Change of clothes',
      'Water bottle',
    ],
    importantInfo: [
      'Must be able to swim',
      'Weight limit: 100kg per person',
      'Weather dependent - reschedule if unsafe',
      'Photos delivered within 48 hours via digital download',
      'Minimum age: 8 years',
    ],
    cancellationPolicy: 'Free cancellation up to 24 hours before start time',
    reviews: {
      averageRating: 5.0,
      totalReviews: 143,
    },
    seoKeywords: [
      'clear kayak Diani',
      'transparent kayak photoshoot Kenya',
      'Diani beach photography',
      'Instagram photoshoot Diani',
      'floating kayak pictures',
      'Kenya beach activities',
    ],
  },

  {
    id: 'act-002',
    slug: 'beach-photoshoot-diani',
    title: 'Diani Beach Professional Photoshoot',
    subtitle: 'Capture timeless memories on Kenya\'s most beautiful beach',
    location: 'Diani Beach',
    region: 'diani',
    category: 'photography',
    type: 'photography',
    price: 10000, // $80 from pricing file
    currency: 'KES',
    duration: '1 hour',
    groupSize: { min: 1, max: 4 },
    difficulty: 'easy',
    featured: true,
    bestFor: ['Couples', 'Families', 'Solo Travelers', 'Honeymoons'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200',
      alt: 'Beach Photoshoot Diani',
      type: 'hero',
    },
    gallery: [],
    description: 'A relaxed coastal shoot along the iconic Diani shoreline. Perfect for solo travelers, couples, or families wanting timeless beach visuals. Our experienced photographers capture the golden hour magic, your genuine moments, and the stunning backdrop of white sand and turquoise waters.',
    highlights: [
      '15 HD edited beach photos',
      '1 short Instagram Reel',
      'Natural beach and shoreline locations',
      'Light posing guidance during shoot',
      'Golden hour timing available',
      'Outfit change allowed',
    ],
    included: [
      'Professional photographer (1 hour)',
      'HD photo editing (15 photos)',
      'Instagram Reel creation',
      'Location scouting',
      'Posing direction',
      'Digital delivery via download link',
    ],
    notIncluded: [
      'Makeup artist',
      'Wardrobe styling',
      'Printed photos',
      'Additional hours',
    ],
    itinerary: [
      { time: '06:00 AM', activity: 'Golden hour option - sunrise shoot' },
      { time: '05:30 PM', activity: 'Golden hour option - sunset shoot' },
      { time: 'Anytime', activity: 'Midday shoots available with shade locations' },
    ],
    meetingPoint: 'Agreed upon Diani Beach access point',
    coordinates: { lat: -4.32, lng: 39.57 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['06:00 AM', '09:00 AM', '05:30 PM'],
      seasonalNotes: 'Available year-round. Golden hour shoots most popular.',
    },
    whatToBring: [
      'Outfit(s) of choice',
      'Props (optional - hats, sunglasses, beach ball)',
      'Comfortable footwear',
      'Hair accessories if needed',
    ],
    importantInfo: [
      'Photos delivered within 48 hours',
      'One outfit change allowed',
      'Recommend bringing backup outfit',
      'Weather dependent',
      'Can reschedule for free if poor conditions',
    ],
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    reviews: {
      averageRating: 4.9,
      totalReviews: 287,
    },
    seoKeywords: [
      'Diani beach photoshoot',
      'professional beach photography Kenya',
      'couple photoshoot Diani',
      'Kenya beach photos',
      'Diani photographer',
      'beach portraits Kenya',
    ],
  },

  {
    id: 'act-003',
    slug: 'combo-beach-kayak-photoshoot',
    title: 'Beach & Kayak Combo Photoshoot',
    subtitle: 'Best of both worlds - beach and ocean photography',
    location: 'Diani Beach',
    region: 'diani',
    category: 'photography',
    type: 'combo',
    price: 20000, // $160 from pricing file (discounted from $190)
    originalPrice: 24000,
    currency: 'KES',
    duration: '2.5 hours',
    groupSize: { min: 1, max: 2 },
    difficulty: 'easy',
    featured: true,
    bestFor: ['Content Creators', 'Instagram Influencers', 'Couples', 'Adventure Seekers'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1200',
      alt: 'Combo Beach and Kayak Photoshoot',
      type: 'hero',
    },
    gallery: [],
    description: 'A complete coastal experience combining serene beach shots and the thrill of clear kayak photography. Ideal for adventurous travelers and content creators wanting diverse, high-quality content from one session. Save $30 by booking this popular combo package.',
    highlights: [
      '10 HD edited beach photos',
      '10 HD edited clear kayak photos',
      '1 cinematic Instagram Reel',
      'Styled guidance for both locations',
      'Best value package',
      'Most popular choice',
    ],
    included: [
      'Professional photography (2.5 hours)',
      'Beach photoshoot session',
      'Clear kayak photoshoot',
      'HD photo editing (20 total photos)',
      'Cinematic Instagram Reel',
      'All kayaking equipment',
      'Safety equipment',
    ],
    notIncluded: [
      'Beach entry fee',
      'Makeup artist',
      'Additional photo edits',
      'Printed photos',
    ],
    itinerary: [
      { time: '08:45 AM', activity: 'Meet and greet at beach access' },
      { time: '09:00 AM', activity: 'Beach photoshoot session (1 hour)' },
      { time: '10:00 AM', activity: 'Equipment setup for kayak shoot' },
      { time: '10:15 AM', activity: 'Kayak photoshoot (1 hour)' },
      { time: '11:15 AM', activity: 'Wrap up and photo review' },
    ],
    meetingPoint: 'Diani Beach Main Access',
    coordinates: { lat: -4.33, lng: 39.56 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '02:00 PM'],
      seasonalNotes: 'Best October-March. Morning sessions preferred.',
    },
    whatToBring: [
      'Swimwear',
      'Beach outfit for photos',
      'Sunscreen',
      'Towel',
      'Water bottle',
      'Change of clothes',
    ],
    importantInfo: [
      'Must be able to swim',
      'All photos delivered within 48 hours',
      'Weather dependent',
      'Free reschedule if conditions unsafe',
      'MOST POPULAR package - books fast!',
    ],
    cancellationPolicy: 'Free cancellation up to 48 hours before',
    reviews: {
      averageRating: 5.0,
      totalReviews: 421,
    },
    seoKeywords: [
      'Diani photoshoot package',
      'beach and kayak photography Kenya',
      'Instagram content creation Diani',
      'best photoshoot Diani',
      'Kenya beach activities photography',
    ],
  },

  {
    id: 'act-004',
    slug: 'jet-ski-adventure-diani',
    title: 'Jet Ski Ocean Adventure',
    subtitle: 'High-speed thrills on the Indian Ocean',
    location: 'Diani Beach',
    region: 'diani',
    category: 'water-sports',
    type: 'adventure',
    price: 8000,
    currency: 'KES',
    duration: '30 minutes',
    groupSize: { min: 1, max: 2 },
    difficulty: 'easy',
    featured: true,
    bestFor: ['Adrenaline Junkies', 'First-Timers', 'Couples'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=1200',
      alt: 'Jet Skiing Diani',
      type: 'hero',
    },
    gallery: [],
    description: 'Feel the rush of speeding across crystal-clear waters on a powerful jet ski. No experience needed - our instructors will get you riding in minutes. Perfect for thrill-seekers wanting an adrenaline boost during their beach vacation.',
    highlights: [
      'Latest model Yamaha jet skis',
      'Safety briefing included',
      'Life jackets provided',
      'Fuel included',
      'Tandem riding available',
      'Photos from shore (optional)',
    ],
    included: [
      'Jet ski rental (30 minutes)',
      'Safety equipment',
      'Brief training session',
      'Fuel',
      'Insurance',
    ],
    notIncluded: [
      'GoPro rental',
      'Photos/videos',
      'Additional time',
      'Beach entry fee',
    ],
    meetingPoint: 'Diani Water Sports Center',
    coordinates: { lat: -4.33, lng: 39.56 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '11:00 AM', '02:00 PM', '04:00 PM'],
      seasonalNotes: 'Best conditions October-March',
    },
    whatToBring: [
      'Swimwear',
      'Sunscreen',
      'Sunglasses with strap',
      'Towel',
    ],
    importantInfo: [
      'Minimum age: 16 years',
      'Valid ID required',
      'Weather dependent',
      'No pregnant women',
      'Tandem: max combined weight 180kg',
    ],
    cancellationPolicy: 'Free cancellation 24 hours before',
    reviews: {
      averageRating: 4.8,
      totalReviews: 532,
    },
    seoKeywords: [
      'jet ski Diani',
      'water sports Diani beach',
      'jet skiing Kenya',
      'Diani beach activities',
      'adventure sports Kenya coast',
    ],
  },

  {
    id: 'act-005',
    slug: 'skydiving-diani',
    title: 'Tandem Skydiving Experience',
    subtitle: 'Jump from 10,000 feet above the Indian Ocean',
    location: 'Diani Beach',
    region: 'diani',
    category: 'adventure',
    type: 'extreme',
    price: 38000,
    currency: 'KES',
    duration: '3 hours (including briefing)',
    groupSize: { min: 1, max: 8 },
    difficulty: 'moderate',
    featured: true,
    bestFor: ['Thrill Seekers', 'Bucket List', 'Adventure Junkies'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1512225535922-54c9965d2e1f?auto=format&fit=crop&w=1200',
      alt: 'Skydiving Diani',
      type: 'hero',
    },
    gallery: [],
    description: 'The ultimate adrenaline rush! Experience the thrill of freefall from 10,000 feet above Diani\'s stunning coastline. Tandem with experienced instructors, you\'ll enjoy 45 seconds of freefall followed by a peaceful 5-minute parachute descent with breathtaking views of the Indian Ocean, coral reefs, and pristine beaches.',
    highlights: [
      'Jump from 10,000 feet',
      '45 seconds freefall',
      'Certified tandem instructors',
      'Spectacular ocean views',
      'Professional video & photos available',
      'All safety equipment included',
    ],
    included: [
      'Tandem jump with certified instructor',
      'All safety equipment',
      'Safety briefing and training',
      'Certificate of completion',
      'Ground support team',
    ],
    notIncluded: [
      'Video & photo package (KES 8,000)',
      'Transport to dropzone',
      'Insurance (optional)',
      'Additional jumps',
    ],
    meetingPoint: 'Diani Skydive Center',
    coordinates: { lat: -4.31, lng: 39.58 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['07:00 AM', '09:00 AM', '11:00 AM', '02:00 PM'],
      seasonalNotes: 'Year-round availability. Best visibility October-March.',
    },
    whatToBring: [
      'Comfortable athletic clothing',
      'Closed-toe athletic shoes',
      'Photo ID',
      'Positive attitude!',
    ],
    importantInfo: [
      'Must be 18+ years old',
      'Weight limit: 95kg max',
      'Medical clearance required if over 40',
      'No heart conditions or recent surgery',
      'Highly weather dependent',
      'Advance booking essential',
    ],
    cancellationPolicy: 'Free cancellation 48 hours before. Weather cancellations = full refund.',
    reviews: {
      averageRating: 5.0,
      totalReviews: 856,
    },
    seoKeywords: [
      'skydiving Diani',
      'Kenya skydive',
      'tandem skydive Diani beach',
      'skydiving Indian Ocean',
      'extreme sports Kenya',
      'bucket list Kenya',
    ],
  },

  {
    id: 'act-006',
    slug: 'horse-riding-beach-diani',
    title: 'Sunset Horse Riding on the Beach',
    subtitle: 'Gallop along pristine shores during golden hour',
    location: 'Diani Beach',
    region: 'diani',
    category: 'adventure',
    type: 'nature',
    price: 7000,
    currency: 'KES',
    duration: '1.5 hours',
    groupSize: { min: 1, max: 6 },
    difficulty: 'easy',
    featured: false,
    bestFor: ['Couples', 'Families', 'Nature Lovers', 'Photographers'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1534330207526-8e81f10ec6fc?auto=format&fit=crop&w=1200',
      alt: 'Horse Riding Diani Beach',
      type: 'hero',
    },
    gallery: [],
    description: 'Experience the romance of riding well-trained horses along Diani\'s pristine shoreline at sunset. Perfect for beginners and experienced riders alike. Witness the sky painted in shades of orange and pink as you trot through shallow waters and soft sand.',
    highlights: [
      'Sunset timing for best photos',
      'Well-trained, gentle horses',
      'Suitable for all skill levels',
      'Ride through shallow waters',
      'Professional guides',
      'Beach gallop experience',
    ],
    included: [
      'Horse rental',
      'Riding helmet',
      'Experienced guide',
      'Safety briefing',
      'Beach access',
    ],
    notIncluded: [
      'Photos (bring your camera)',
      'Riding boots (available for rent KES 500)',
      'Insurance',
      'Tips for guide',
    ],
    meetingPoint: 'Diani Beach Stables',
    coordinates: { lat: -4.34, lng: 39.55 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['05:30 PM'],
      seasonalNotes: 'Sunset times vary by season. Contact for exact time.',
    },
    whatToBring: [
      'Comfortable long pants',
      'Closed-toe shoes',
      'Sunscreen',
      'Camera',
      'Water bottle',
    ],
    importantInfo: [
      'Weight limit: 90kg',
      'Minimum age: 8 years',
      'No horse riding experience needed',
      'Advance booking recommended',
      'Weather dependent',
    ],
    cancellationPolicy: 'Free cancellation 24 hours before',
    reviews: {
      averageRating: 4.9,
      totalReviews: 324,
    },
    seoKeywords: [
      'horse riding Diani',
      'beach horse riding Kenya',
      'sunset horse ride Diani',
      'horseback riding Indian Ocean',
      'romantic activities Diani',
    ],
  },

  // ============================================================================
  // WATAMU ACTIVITIES
  // ============================================================================

  {
    id: 'act-007',
    slug: 'snorkeling-watamu-marine-park',
    title: 'Watamu Marine Park Snorkeling',
    subtitle: 'Discover vibrant coral gardens and tropical fish',
    location: 'Watamu Marine Park',
    region: 'watamu',
    category: 'water-sports',
    type: 'marine',
    price: 6000,
    currency: 'KES',
    duration: '3 hours',
    groupSize: { min: 2, max: 15 },
    difficulty: 'easy',
    featured: true,
    bestFor: ['Families', 'First-Timers', 'Marine Life Enthusiasts'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200',
      alt: 'Snorkeling Watamu',
      type: 'hero',
    },
    gallery: [],
    description: 'Explore Watamu\'s world-renowned coral reefs teeming with colorful fish, sea turtles, and marine life. Crystal-clear waters offer visibility up to 20 meters. Perfect for beginners and families. Marine park conservation fees support local reef protection.',
    highlights: [
      'Vibrant coral gardens',
      'Sea turtle encounters',
      '100+ fish species',
      'Crystal clear waters',
      'Marine park certified guides',
      'All equipment provided',
    ],
    included: [
      'Boat transfer to reef',
      'Snorkeling equipment',
      'Life jacket',
      'Marine park fees',
      'Experienced guide',
      'Drinking water',
    ],
    notIncluded: [
      'Underwater camera rental (KES 1,500)',
      'Wetsuit rental (KES 800)',
      'Photos/videos',
      'Lunch',
    ],
    meetingPoint: 'Watamu Beach, Ocean Sports Jetty',
    coordinates: { lat: -3.37, lng: 40.03 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['08:30 AM', '11:00 AM', '01:30 PM'],
      seasonalNotes: 'Best visibility October-March. Year-round availability.',
    },
    whatToBring: [
      'Swimwear',
      'Reef-safe sunscreen',
      'Towel',
      'Waterproof camera',
      'Light cover-up',
    ],
    importantInfo: [
      'Must be able to swim',
      'Minimum age: 6 years',
      'Eco-friendly - no touching coral',
      'Tide dependent',
      'Life jackets mandatory',
    ],
    cancellationPolicy: 'Free cancellation 24 hours before',
    reviews: {
      averageRating: 4.9,
      totalReviews: 1243,
    },
    seoKeywords: [
      'snorkeling Watamu',
      'Watamu marine park',
      'coral reef Kenya',
      'snorkeling Kenya coast',
      'Watamu activities',
      'sea turtle snorkeling',
    ],
  },

  {
    id: 'act-008',
    slug: 'scuba-diving-watamu',
    title: 'PADI Scuba Diving - Watamu Reefs',
    subtitle: 'Explore underwater paradise with certified instructors',
    location: 'Watamu',
    region: 'watamu',
    category: 'water-sports',
    type: 'diving',
    price: 13500,
    currency: 'KES',
    duration: '3-4 hours',
    groupSize: { min: 2, max: 6 },
    difficulty: 'moderate',
    featured: true,
    bestFor: ['Certified Divers', 'First-Time Divers', 'Marine Enthusiasts'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=1200',
      alt: 'Scuba Diving Watamu',
      type: 'hero',
    },
    gallery: [],
    description: 'Dive into Watamu\'s pristine underwater world with PADI certified instructors. Explore vibrant coral gardens, encounter sea turtles, rays, and countless tropical fish species. Suitable for beginners (Discover Scuba) and certified divers. Underwater visibility averages 15-20 meters.',
    highlights: [
      'PADI certified instruction',
      'Vibrant coral reefs',
      'Sea turtle encounters',
      'Tropical fish paradise',
      'Small group sizes',
      'Beginner-friendly',
    ],
    included: [
      'All diving equipment',
      'PADI instructor',
      'Boat transfer',
      'Marine park fees',
      'Drinking water',
      'Insurance',
    ],
    notIncluded: [
      'Underwater camera rental',
      'Certification course fees',
      'Lunch',
      'Transport to dive center',
    ],
    meetingPoint: 'Watamu Dive Center, Turtle Bay',
    coordinates: { lat: -3.37, lng: 40.03 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['08:00 AM', '01:00 PM'],
      seasonalNotes: 'Best visibility October-March',
    },
    whatToBring: [
      'Swimwear',
      'Towel',
      'Reef-safe sunscreen',
      'PADI certification (if certified)',
      'Underwater camera',
    ],
    importantInfo: [
      'Medical form required',
      'No flying 24 hours after dive',
      'No alcohol before diving',
      'Minimum age: 10 years',
      'Certification check for experienced divers',
    ],
    cancellationPolicy: 'Free cancellation 48 hours before',
    reviews: {
      averageRating: 4.9,
      totalReviews: 687,
    },
    seoKeywords: [
      'scuba diving Watamu',
      'PADI diving Kenya',
      'Watamu dive sites',
      'learn to dive Kenya',
      'diving Indian Ocean',
    ],
  },

  {
    id: 'act-009',
    slug: 'dolphin-watching-watamu',
    title: 'Dolphin Watching Boat Tour',
    subtitle: 'Encounter wild dolphins in their natural habitat',
    location: 'Watamu',
    region: 'watamu',
    category: 'wildlife',
    type: 'marine',
    price: 8000,
    currency: 'KES',
    duration: '3 hours',
    groupSize: { min: 2, max: 12 },
    difficulty: 'easy',
    featured: true,
    bestFor: ['Families', 'Wildlife Lovers', 'Photographers', 'Nature Enthusiasts'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=1200',
      alt: 'Dolphin Watching Watamu',
      type: 'hero',
    },
    gallery: [],
    description: 'Set sail into Watamu\'s crystal waters in search of playful bottlenose and spinner dolphins. Watch these magnificent creatures leap, play, and swim alongside your traditional dhow boat. Snorkeling opportunities included at pristine coral gardens. Conservation-focused tour with experienced marine guides.',
    highlights: [
      'Wild dolphin encounters',
      'Traditional dhow boat',
      'Snorkeling included',
      'Expert marine guides',
      'Small group experience',
      'Eco-tourism certified',
    ],
    included: [
      'Dhow boat cruise',
      'Snorkeling equipment',
      'Marine guide',
      'Life jackets',
      'Drinking water',
      'Light snacks',
    ],
    notIncluded: [
      'Underwater camera',
      'Full lunch',
      'Transport to jetty',
      'Professional photos',
    ],
    meetingPoint: 'Watamu Jetty, near Ocean Sports',
    coordinates: { lat: -3.37, lng: 40.03 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['07:00 AM', '10:00 AM'],
      seasonalNotes: 'Best sightings October-March. 90% encounter rate.',
    },
    whatToBring: [
      'Swimwear',
      'Sunscreen',
      'Hat and sunglasses',
      'Camera (waterproof)',
      'Towel',
    ],
    importantInfo: [
      'Dolphin sightings not 100% guaranteed',
      '90% success rate',
      'No swimming with dolphins (conservation)',
      'Eco-friendly guidelines enforced',
      'Suitable for all ages',
    ],
    cancellationPolicy: 'Free cancellation 24 hours before',
    reviews: {
      averageRating: 4.8,
      totalReviews: 543,
    },
    seoKeywords: [
      'dolphin watching Watamu',
      'dolphins Kenya coast',
      'marine life Watamu',
      'dhow boat trip Watamu',
      'wildlife tours Kenya',
    ],
  },

  {
    id: 'act-010',
    slug: 'deep-sea-fishing-watamu',
    title: 'Deep Sea Fishing Charter',
    subtitle: 'Battle marlin, sailfish, and tuna in legendary waters',
    location: 'Watamu',
    region: 'watamu',
    category: 'water-sports',
    type: 'fishing',
    price: 35000,
    currency: 'KES',
    duration: 'Half Day (5 hours)',
    groupSize: { min: 2, max: 6 },
    difficulty: 'moderate',
    featured: false,
    bestFor: ['Fishing Enthusiasts', 'Groups', 'Adventure Seekers'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?auto=format&fit=crop&w=1200',
      alt: 'Deep Sea Fishing Watamu',
      type: 'hero',
    },
    gallery: [],
    description: 'Watamu is world-renowned for big game fishing. Head offshore in search of marlin, sailfish, barracuda, kingfish, and yellowfin tuna. Our experienced captains know the best spots and provide all equipment. Catch and release or keep your trophy - your choice!',
    highlights: [
      'Professional captain & crew',
      'Top-quality fishing gear',
      'Prime fishing grounds',
      'Marlin & sailfish season',
      'All equipment included',
      'Cooler with ice provided',
    ],
    included: [
      'Fishing boat charter',
      'Captain and crew',
      'All fishing equipment',
      'Bait and tackle',
      'Fuel',
      'Drinks and snacks',
    ],
    notIncluded: [
      'Fishing license (KES 2,000)',
      'Full lunch',
      'Transport to marina',
      'Fish cleaning service',
    ],
    meetingPoint: 'Watamu Marine Association Jetty',
    coordinates: { lat: -3.37, lng: 40.03 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['06:00 AM'],
      seasonalNotes: 'Best season November-March. Advance booking essential.',
    },
    whatToBring: [
      'Sunscreen (high SPF)',
      'Hat and sunglasses',
      'Light long-sleeve shirt',
      'Camera',
      'Seasickness tablets if needed',
    ],
    importantInfo: [
      'Fishing license required',
      'Catch and release encouraged',
      'Tag & release for conservation',
      'Experience not required',
      'Minimum age: 10 years',
    ],
    cancellationPolicy: 'Free cancellation 48 hours before',
    reviews: {
      averageRating: 4.9,
      totalReviews: 234,
    },
    seoKeywords: [
      'deep sea fishing Watamu',
      'marlin fishing Kenya',
      'big game fishing Watamu',
      'sport fishing Kenya coast',
      'fishing charter Watamu',
    ],
  },

  // ============================================================================
  // MALINDI ACTIVITIES
  // ============================================================================

  {
    id: 'act-011',
    slug: 'kite-surfing-che-shale-malindi',
    title: 'Kite Surfing Lessons - Che Shale',
    subtitle: 'Learn to fly across Malindi\'s perfect waters',
    location: 'Che Shale, Malindi',
    region: 'malindi',
    category: 'water-sports',
    type: 'extreme',
    price: 12000,
    currency: 'KES',
    duration: '2 hours',
    groupSize: { min: 1, max: 4 },
    difficulty: 'moderate',
    featured: true,
    bestFor: ['Adventure Seekers', 'Water Sports Enthusiasts', 'Fitness Lovers'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1537519646099-335be2dc3f33?auto=format&fit=crop&w=1200',
      alt: 'Kite Surfing Malindi',
      type: 'hero',
    },
    gallery: [],
    description: 'Che Shale beach near Malindi offers perfect conditions for kite surfing with consistent winds and flat water lagoons. Whether you\'re a complete beginner or improving your skills, our IKO certified instructors will get you riding. Experience the ultimate freedom of being powered by the wind.',
    highlights: [
      'IKO certified instructors',
      'All equipment provided',
      'Perfect wind conditions',
      'Flat water lagoon for learning',
      'Small class sizes',
      'Progression guaranteed',
    ],
    included: [
      'Kite surfing equipment',
      'Safety gear & helmet',
      'IKO instructor',
      'Theory & practice session',
      'Beach access',
    ],
    notIncluded: [
      'Wetsuit (available for rent)',
      'GoPro rental',
      'Additional hours',
      'IKO certification exam',
    ],
    meetingPoint: 'Che Shale Kite School',
    coordinates: { lat: -3.15, lng: 40.15 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '02:00 PM'],
      seasonalNotes: 'Best winds December-March. Year-round availability.',
    },
    whatToBring: [
      'Swimwear',
      'Sunscreen',
      'Towel',
      'Rash guard (recommended)',
      'Water bottle',
    ],
    importantInfo: [
      'Must be able to swim',
      'Minimum age: 12 years',
      'Weight: 45kg-100kg',
      'Good fitness level helpful',
      'Multi-day courses available',
    ],
    cancellationPolicy: 'Free cancellation 24 hours before',
    reviews: {
      averageRating: 4.9,
      totalReviews: 345,
    },
    seoKeywords: [
      'kite surfing Malindi',
      'kite boarding Kenya',
      'water sports Malindi',
      'learn kite surfing Kenya',
      'Che Shale beach',
    ],
  },

  {
    id: 'act-012',
    slug: 'stand-up-paddle-boarding-malindi',
    title: 'Stand Up Paddle Boarding (SUP)',
    subtitle: 'Glide peacefully across Malindi\'s calm waters',
    location: 'Malindi',
    region: 'malindi',
    category: 'water-sports',
    type: 'leisure',
    price: 3500,
    currency: 'KES',
    duration: '1.5 hours',
    groupSize: { min: 1, max: 8 },
    difficulty: 'easy',
    featured: false,
    bestFor: ['Beginners', 'Families', 'Fitness', 'Sunset Lovers'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&w=1200',
      alt: 'SUP Malindi',
      type: 'hero',
    },
    gallery: [],
    description: 'Stand up paddle boarding is the perfect way to explore Malindi\'s coastline at your own pace. Easy to learn and suitable for all ages and fitness levels. Enjoy a peaceful morning or stunning sunset session gliding across calm, clear waters.',
    highlights: [
      'Easy to learn',
      'Suitable for all ages',
      'Calm protected waters',
      'Sunset sessions available',
      'Great workout',
      'Eco-friendly',
    ],
    included: [
      'SUP board rental',
      'Paddle',
      'Safety leash',
      'Life jacket',
      'Basic instruction',
    ],
    notIncluded: [
      'Waterproof camera',
      'Transport',
      'Wetsuit',
      'Additional time',
    ],
    meetingPoint: 'Malindi Beach, near Driftwood Hotel',
    coordinates: { lat: -3.22, lng: 40.12 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['07:00 AM', '09:00 AM', '05:00 PM'],
      seasonalNotes: 'Year-round availability',
    },
    whatToBring: [
      'Swimwear',
      'Sunscreen',
      'Hat',
      'Water bottle',
      'Towel',
    ],
    importantInfo: [
      'Basic swimming ability required',
      'Minimum age: 8 years',
      'Tide dependent',
      'Calm conditions only',
      'Great for beginners',
    ],
    cancellationPolicy: 'Free cancellation 12 hours before',
    reviews: {
      averageRating: 4.7,
      totalReviews: 287,
    },
    seoKeywords: [
      'SUP Malindi',
      'paddle boarding Kenya',
      'stand up paddle Kenya coast',
      'water activities Malindi',
    ],
  },

  {
    id: 'act-013',
    slug: 'gede-ruins-cultural-tour',
    title: 'Gede Ruins Historical Tour',
    subtitle: 'Explore ancient Swahili city ruins',
    location: 'Gede, near Malindi',
    region: 'malindi',
    category: 'cultural',
    type: 'historical',
    price: 2500,
    currency: 'KES',
    duration: '2 hours',
    groupSize: { min: 1, max: 20 },
    difficulty: 'easy',
    featured: false,
    bestFor: ['History Buffs', 'Families', 'Photographers', 'Culture Seekers'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1568736253690-80a5f58fa4c5?auto=format&fit=crop&w=1200',
      alt: 'Gede Ruins',
      type: 'hero',
    },
    gallery: [],
    description: 'Step back in time at the mysterious Gede Ruins, an ancient Swahili town dating back to the 13th century. Wander through coral-built structures, see ancient mosques, tombs, and houses hidden in coastal forest. Learn about Swahili trade, culture, and the mysteries of this abandoned city.',
    highlights: [
      '13th-century Swahili ruins',
      'Ancient mosques and tombs',
      'Forest-shrouded architecture',
      'Expert guide narration',
      'Butterfly pavilion',
      'Historical artifacts',
    ],
    included: [
      'Entry fees',
      'Expert guide',
      'Butterfly pavilion access',
      'Small museum visit',
    ],
    notIncluded: [
      'Transport to/from Gede',
      'Food and drinks',
      'Souvenirs',
    ],
    meetingPoint: 'Gede Ruins Main Entrance',
    coordinates: { lat: -3.30, lng: 40.02 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['08:00 AM', '10:00 AM', '02:00 PM'],
      seasonalNotes: 'Open year-round. Morning tours cooler.',
    },
    whatToBring: [
      'Comfortable walking shoes',
      'Hat and sunscreen',
      'Water bottle',
      'Camera',
      'Insect repellent',
    ],
    importantInfo: [
      'Moderate walking involved',
      'Uneven surfaces',
      'Shaded paths',
      'Educational for children',
      'Suitable for all ages',
    ],
    cancellationPolicy: 'Free cancellation 12 hours before',
    reviews: {
      averageRating: 4.6,
      totalReviews: 432,
    },
    seoKeywords: [
      'Gede ruins',
      'historical sites Kenya',
      'Swahili culture',
      'Malindi attractions',
      'ancient ruins Kenya',
    ],
  },

  {
    id: 'act-014',
    slug: 'malindi-marine-park-glass-boat',
    title: 'Glass Bottom Boat Tour',
    subtitle: 'View coral reefs without getting wet',
    location: 'Malindi Marine Park',
    region: 'malindi',
    category: 'water-sports',
    type: 'marine',
    price: 4500,
    currency: 'KES',
    duration: '2 hours',
    groupSize: { min: 2, max: 20 },
    difficulty: 'easy',
    featured: false,
    bestFor: ['Families', 'Non-Swimmers', 'Elderly', 'Kids'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=1200',
      alt: 'Glass Boat Malindi',
      type: 'hero',
    },
    gallery: [],
    description: 'Perfect for non-swimmers and families! View Malindi Marine Park\'s stunning coral reefs and tropical fish through glass panels in the boat floor. Stay dry while enjoying the underwater world. Educational marine guide explains reef ecology and fish species.',
    highlights: [
      'No swimming required',
      'View coral reefs from boat',
      'Family-friendly',
      'Educational commentary',
      'Comfortable seating',
      'Shade available',
    ],
    included: [
      'Glass bottom boat ride',
      'Marine park fees',
      'Expert guide',
      'Drinking water',
      'Life jackets',
    ],
    notIncluded: [
      'Snacks',
      'Photos',
      'Transport to jetty',
    ],
    meetingPoint: 'Malindi Jetty',
    coordinates: { lat: -3.22, lng: 40.12 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '11:00 AM', '02:00 PM'],
      seasonalNotes: 'Year-round. Best visibility morning hours.',
    },
    whatToBring: [
      'Sunscreen',
      'Hat',
      'Camera',
      'Sunglasses',
    ],
    importantInfo: [
      'Suitable for all ages',
      'Wheelchair accessible',
      'Non-swimmers welcome',
      'Tide dependent',
      'Calm conditions only',
    ],
    cancellationPolicy: 'Free cancellation 12 hours before',
    reviews: {
      averageRating: 4.5,
      totalReviews: 567,
    },
    seoKeywords: [
      'glass boat Malindi',
      'Malindi marine park',
      'coral viewing Kenya',
      'family activities Malindi',
      'non-swimming marine tour',
    ],
  },

  // Additional unique activities
  {
    id: 'act-015',
    slug: 'windsurfing-lessons-malindi',
    title: 'Windsurfing Beginner Lessons',
    subtitle: 'Master the art of wind-powered surfing',
    location: 'Malindi',
    region: 'malindi',
    category: 'water-sports',
    type: 'extreme',
    price: 9000,
    currency: 'KES',
    duration: '2 hours',
    groupSize: { min: 1, max: 4 },
    difficulty: 'moderate',
    featured: false,
    bestFor: ['Water Sports Enthusiasts', 'Fitness Lovers', 'Adventure Seekers'],
    coverImage: {
      url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200',
      alt: 'Windsurfing Malindi',
      type: 'hero',
    },
    gallery: [],
    description: 'Learn windsurfing in Malindi\'s ideal conditions with consistent winds and warm waters. Perfect for beginners with our step-by-step progression method. From balance and sail control to your first rides - we\'ll get you gliding across the water.',
    highlights: [
      'Certified instructors',
      'Modern equipment',
      'Sheltered bay for learning',
      'Progressive teaching method',
      'Small class sizes',
      'Multiple lesson packages',
    ],
    included: [
      'Windsurf board and sail',
      'Wetsuit',
      'Safety gear',
      'Certified instructor',
      'Beach access',
    ],
    notIncluded: [
      'Photos/videos',
      'Additional hours',
      'Advanced equipment',
    ],
    meetingPoint: 'Malindi Windsurfing Center',
    coordinates: { lat: -3.21, lng: 40.13 },
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '02:00 PM'],
      seasonalNotes: 'Best winds December-March',
    },
    whatToBring: [
      'Swimwear',
      'Sunscreen',
      'Towel',
      'Water bottle',
    ],
    importantInfo: [
      'Must be able to swim',
      'Minimum age: 10 years',
      'Good fitness level helpful',
      'Multi-lesson packages available',
    ],
    cancellationPolicy: 'Free cancellation 24 hours before',
    reviews: {
      averageRating: 4.7,
      totalReviews: 176,
    },
    seoKeywords: [
      'windsurfing Malindi',
      'learn windsurf Kenya',
      'water sports Malindi',
      'surf lessons Kenya coast',
    ],
  },
];

// Helper functions
export function getActivitiesByRegion(region: string) {
  return activities.filter((activity) => activity.region.toLowerCase() === region.toLowerCase());
}

export function getActivitiesByCategory(category: string) {
  return activities.filter((activity) => activity.category === category);
}

export function getFeaturedActivities() {
  return activities.filter((activity) => activity.featured);
}

export function getActivityBySlug(slug: string) {
  return activities.find((activity) => activity.slug === slug);
}

export const activityCategories = [
  { id: 'all', label: 'All Activities', slug: 'all' },
  { id: 'water-sports', label: 'Water Sports', slug: 'water-sports' },
  { id: 'photography', label: 'Photography', slug: 'photography' },
  { id: 'adventure', label: 'Adventure', slug: 'adventure' },
  { id: 'wildlife', label: 'Wildlife', slug: 'wildlife' },
  { id: 'cultural', label: 'Cultural', slug: 'cultural' },
];

export const activityRegions = [
  { id: 'all', label: 'All Locations', slug: 'all' },
  { id: 'diani', label: 'Diani Beach', slug: 'diani' },
  { id: 'watamu', label: 'Watamu', slug: 'watamu' },
  { id: 'malindi', label: 'Malindi', slug: 'malindi' },
];