import { Experience } from './types';

export const experiences: Experience[] = [
  {
    id: 'exp-1',
    slug: 'great-migration-safari',
    title: 'Great Migration Safari Experience',
    category: 'safari',
    tagline: 'Witness nature\'s greatest spectacle',
    description: 'Experience the drama of the Great Migration firsthand. Watch millions of wildebeest brave the crocodile-infested Mara River, witness predator-prey interactions, and capture once-in-a-lifetime photographs. Our expert guides know the best vantage points and timing to maximize your experience.',
    duration: '3 Days / 2 Nights',
    groupSize: { min: 2, max: 6 },
    price: 85000,
    currency: 'Ksh',
    highlights: [
      'Mara River crossing viewing',
      'Big Five game drives',
      'Professional photography guidance',
      'Sunrise & sunset game drives',
      'Luxury tented camp accommodation',
      'All meals included',
    ],
    included: [
      'Park entry fees',
      'Professional guide',
      'Game drives in 4x4 vehicle',
      'Accommodation (2 nights)',
      'All meals and bottled water',
      'Binoculars',
      'Field guidebooks',
    ],
    notIncluded: [
      'Tips for guide',
      'Personal travel insurance',
      'Drinks at the lodge',
      'Hot air balloon safari (optional)',
    ],
    location: 'Maasai Mara National Reserve',
    meetingPoint: 'Pickup from Nairobi hotels or Wilson Airport',
    coordinates: { lat: -1.4061, lng: 35.0050 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200',
      alt: 'Wildebeest Migration',
      type: 'hero',
    },
    gallery: [
      {
        url: 'https://images.unsplash.com/photo-1493246507139-91e8bef99c02?auto=format&fit=crop&w=800',
        alt: 'River Crossing',
      },
      {
        url: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800',
        alt: 'Safari Vehicle',
      },
    ],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['06:00 AM'],
      seasonalAvailability: 'Best: July-October',
    },
    difficulty: 'easy',
    featured: true,
    averageRating: 5.0,
  },

  {
    id: 'exp-2',
    slug: 'maasai-cultural-immersion',
    title: 'Maasai Cultural Immersion Day',
    category: 'cultural',
    tagline: 'A day in the life of Maasai warriors',
    description: 'Spend a full day immersed in Maasai culture. Learn traditional beadwork, participate in warrior training, understand their deep connection with cattle, and share authentic meals. This isn\'t a tourist show – it\'s a genuine cultural exchange with a welcoming Maasai family.',
    duration: 'Full Day (8 hours)',
    groupSize: { min: 2, max: 8 },
    price: 15000,
    currency: 'Ksh',
    highlights: [
      'Authentic village visit',
      'Traditional warrior training',
      'Beadwork workshop',
      'Cattle herding experience',
      'Traditional Maasai meal',
      'Storytelling by elders',
    ],
    included: [
      'Village entry fee',
      'Cultural guide',
      'All activities',
      'Traditional lunch',
      'Transportation from nearby lodges',
      'Take-home beadwork',
    ],
    notIncluded: [
      'Tips (appreciated)',
      'Additional crafts purchase',
      'Personal expenses',
    ],
    location: 'Maasai Mara Region',
    meetingPoint: 'Your lodge or campsite',
    coordinates: { lat: -1.48, lng: 35.12 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?auto=format&fit=crop&w=1200',
      alt: 'Maasai Warriors',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM'],
    },
    difficulty: 'easy',
    featured: true,
    averageRating: 4.9,
  },

  {
    id: 'exp-3',
    slug: 'mount-kenya-trekking',
    title: 'Mount Kenya Point Lenana Trek',
    category: 'adventure',
    tagline: 'Summit Africa\'s second-highest peak',
    description: 'A challenging but rewarding 5-day trek to Point Lenana (4,985m), the trekking peak of Mount Kenya. Pass through diverse vegetation zones from bamboo forests to alpine desert, acclimatize properly, and summit at sunrise for spectacular views.',
    duration: '5 Days / 4 Nights',
    groupSize: { min: 2, max: 6 },
    price: 75000,
    currency: 'Ksh',
    highlights: [
      'Summit Point Lenana at sunrise',
      'Traverse 5 vegetation zones',
      'Mountain hut accommodation',
      'Professional mountain guides',
      'Porter service included',
      'Certificate of achievement',
    ],
    included: [
      'Park fees',
      'Mountain guides & porters',
      'Hut accommodation',
      'All meals on mountain',
      'Emergency evacuation insurance',
      'Climbing equipment',
    ],
    notIncluded: [
      'Personal hiking gear',
      'Tips for guides/porters',
      'Nairobi accommodation',
      'Personal insurance',
    ],
    location: 'Mount Kenya National Park',
    meetingPoint: 'Nanyuki Town or your Nanyuki accommodation',
    coordinates: { lat: -0.1500, lng: 37.3083 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200',
      alt: 'Mount Kenya Peak',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [1, 2, 3, 4, 5],
      startTimes: ['07:00 AM'],
      seasonalAvailability: 'Best: January-February, July-October',
    },
    difficulty: 'challenging',
    featured: true,
    averageRating: 4.8,
  },

  {
    id: 'exp-4',
    slug: 'diani-kite-surfing-lesson',
    title: 'Kite Surfing Lessons - Diani Beach',
    category: 'adventure',
    tagline: 'Ride the Indian Ocean winds',
    description: 'Learn to kite surf on one of the world\'s best kite beaches. Diani\'s consistent winds and shallow waters make it perfect for beginners. Our IKO-certified instructors ensure a safe and fun learning experience.',
    duration: '3 hours',
    groupSize: { min: 1, max: 4 },
    price: 12000,
    currency: 'Ksh',
    highlights: [
      'IKO certified instructors',
      'All equipment provided',
      'Perfect beginner conditions',
      'Radio helmet communication',
      'Progress at your own pace',
      'Beach safety briefing',
    ],
    included: [
      'Equipment rental',
      'Instructor',
      'Safety gear',
      '3-hour session',
    ],
    notIncluded: [
      'Beach entry fee',
      'Photos/videos',
      'Additional sessions',
    ],
    location: 'Diani Beach',
    meetingPoint: 'Diani Beach Kite School',
    coordinates: { lat: -4.33, lng: 39.56 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1535398089889-dd807df1dfaa?auto=format&fit=crop&w=1200',
      alt: 'Kite Surfing Diani',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['10:00 AM', '02:00 PM'],
      seasonalAvailability: 'Best winds: June-March',
    },
    difficulty: 'moderate',
    featured: false,
    averageRating: 4.7,
  },

  {
    id: 'exp-5',
    slug: 'nairobi-street-food-tour',
    title: 'Nairobi Street Food & Culture Tour',
    category: 'food-wine',
    tagline: 'Taste the flavors of Kenya\'s capital',
    description: 'Explore Nairobi\'s vibrant food scene with a local guide. Sample nyama choma, pilau, mandazi, and other Kenyan favorites while learning about the city\'s history and culture. Visit local markets, street vendors, and hidden gems.',
    duration: '4 hours',
    groupSize: { min: 2, max: 10 },
    price: 6500,
    currency: 'Ksh',
    highlights: [
      '10+ food tastings',
      'Local markets exploration',
      'Cultural insights',
      'Safe and vetted vendors',
      'Vegetarian options available',
      'Small group experience',
    ],
    included: [
      'All food tastings',
      'Local guide',
      'Bottled water',
      'Transport between stops',
    ],
    notIncluded: [
      'Additional drinks',
      'Tips for guide',
      'Hotel pickup/dropoff',
    ],
    location: 'Nairobi City Center',
    meetingPoint: 'Kenyatta Avenue, near Hilton Hotel',
    coordinates: { lat: -1.2864, lng: 36.8172 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200',
      alt: 'Kenyan Street Food',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [1, 2, 3, 4, 5, 6],
      startTimes: ['11:00 AM', '05:00 PM'],
    },
    difficulty: 'easy',
    featured: false,
    averageRating: 4.9,
  },

  {
    id: 'exp-6',
    slug: 'lamu-dhow-sailing-sunset',
    title: 'Traditional Dhow Sailing at Sunset',
    category: 'cultural',
    tagline: 'Sail like the Swahili traders',
    description: 'Experience the timeless tradition of dhow sailing as the sun sets over the Indian Ocean. These traditional wooden boats have been used for centuries along the Swahili coast. Enjoy snacks and fresh coconut water as you glide through turquoise waters.',
    duration: '3 hours',
    groupSize: { min: 2, max: 8 },
    price: 8000,
    currency: 'Ksh',
    highlights: [
      'Traditional dhow sailing',
      'Sunset views',
      'Swahili snacks & drinks',
      'Local captain stories',
      'Swimming stop (optional)',
      'Romantic atmosphere',
    ],
    included: [
      'Dhow rental',
      'Captain & crew',
      'Snacks & drinks',
      'Life jackets',
    ],
    notIncluded: [
      'Hotel transfers',
      'Additional drinks',
      'Tips for crew',
    ],
    location: 'Lamu Island',
    meetingPoint: 'Lamu Waterfront',
    coordinates: { lat: -2.27, lng: 40.90 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200',
      alt: 'Traditional Dhow Sailing',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['04:30 PM'],
    },
    difficulty: 'easy',
    featured: true,
    averageRating: 5.0,
  },

  {
    id: 'exp-7',
    slug: 'coffee-farm-tour-nyeri',
    title: 'Coffee Farm to Cup Experience',
    category: 'food-wine',
    tagline: 'From cherry to cup in Kenya\'s highlands',
    description: 'Discover why Kenyan coffee is world-renowned. Walk through coffee plantations, learn the picking process, witness roasting, and master the art of cupping. Perfect for coffee enthusiasts wanting to understand their morning brew.',
    duration: '3 hours',
    groupSize: { min: 2, max: 12 },
    price: 5000,
    currency: 'Ksh',
    highlights: [
      'Coffee plantation walk',
      'Picking demonstration',
      'Roasting process',
      'Professional cupping session',
      'Coffee tasting',
      'Take home fresh beans',
    ],
    included: [
      'Farm tour',
      'Expert guide',
      'Coffee tastings',
      '250g coffee beans',
      'Light refreshments',
    ],
    notIncluded: [
      'Transport to farm',
      'Additional coffee purchases',
    ],
    location: 'Nyeri Coffee Estate',
    meetingPoint: 'Estate entrance',
    coordinates: { lat: -0.42, lng: 36.95 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200',
      alt: 'Coffee Plantation',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '02:00 PM'],
    },
    difficulty: 'easy',
    featured: false,
    averageRating: 4.8,
  },

  {
    id: 'exp-8',
    slug: 'hell-s-gate-cycling-safari',
    title: 'Hell\'s Gate Cycling & Hiking Safari',
    category: 'adventure',
    tagline: 'Bike among zebras and giraffes',
    description: 'One of the few parks in Kenya where you can explore on foot and bicycle. Cycle through dramatic gorges, spot wildlife up close, and hike through the spectacular Hell\'s Gate Gorge. An adventure unlike any other safari.',
    duration: 'Full Day (6-7 hours)',
    groupSize: { min: 2, max: 8 },
    price: 9500,
    currency: 'Ksh',
    highlights: [
      'Cycling among wildlife',
      'Gorge hiking',
      'Rock climbing (optional)',
      'Fischer\'s Tower viewpoint',
      'Geothermal features',
      'Picnic lunch',
    ],
    included: [
      'Park fees',
      'Bicycle rental',
      'Guide',
      'Packed lunch',
      'Bottled water',
    ],
    notIncluded: [
      'Rock climbing equipment',
      'Personal gear',
      'Tips',
    ],
    location: 'Hell\'s Gate National Park',
    meetingPoint: 'Park main gate',
    coordinates: { lat: -0.91, lng: 36.31 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=1200',
      alt: 'Hell\'s Gate Gorge',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['08:00 AM'],
    },
    difficulty: 'moderate',
    featured: false,
    averageRating: 4.7,
  },

  {
    id: 'exp-9',
    slug: 'watamu-snorkeling-marine-park',
    title: 'Watamu Marine Park Snorkeling',
    category: 'adventure',
    tagline: 'Discover underwater coral gardens',
    description: 'Explore one of Kenya\'s most pristine marine parks. Snorkel over vibrant coral gardens teeming with tropical fish, spot sea turtles, and marvel at the underwater world. Perfect for beginners and experienced snorkelers.',
    duration: '3 hours',
    groupSize: { min: 2, max: 10 },
    price: 6000,
    currency: 'Ksh',
    highlights: [
      'Vibrant coral reefs',
      'Sea turtle sightings',
      'Tropical fish',
      'Crystal clear waters',
      'Professional guides',
      'All equipment provided',
    ],
    included: [
      'Marine park fees',
      'Snorkeling equipment',
      'Guide',
      'Boat transfer',
      'Life jackets',
    ],
    notIncluded: [
      'Underwater camera',
      'Wetsuits',
      'Refreshments',
    ],
    location: 'Watamu Marine National Park',
    meetingPoint: 'Watamu Beach',
    coordinates: { lat: -3.37, lng: 40.03 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=1200',
      alt: 'Coral Reef Snorkeling',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '02:00 PM'],
      seasonalAvailability: 'Best visibility: October-March',
    },
    difficulty: 'easy',
    featured: false,
    averageRating: 4.8,
  },

  {
    id: 'exp-10',
    slug: 'nairobi-photography-workshop',
    title: 'Urban Photography Workshop',
    category: 'photography',
    tagline: 'Capture Nairobi through your lens',
    description: 'A hands-on photography workshop exploring Nairobi\'s contrasts. Learn street photography, portrait techniques, and how to tell stories through images. Suitable for all skill levels from smartphone photographers to DSLR users.',
    duration: '4 hours',
    groupSize: { min: 3, max: 8 },
    price: 7500,
    currency: 'Ksh',
    highlights: [
      'Street photography techniques',
      'Portrait sessions with locals',
      'Architecture & cityscape shots',
      'Post-processing tips',
      'Professional photographer guide',
      'Photo review session',
    ],
    included: [
      'Professional guide',
      'Location permits',
      'Model fees',
      'Coffee break',
      'Photo critique',
    ],
    notIncluded: [
      'Camera equipment',
      'Lunch',
      'Printing services',
    ],
    location: 'Nairobi City Center',
    meetingPoint: 'Sarova Stanley Hotel',
    coordinates: { lat: -1.2864, lng: 36.8172 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=1200',
      alt: 'Urban Photography',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [2, 4, 6],
      startTimes: ['09:00 AM'],
    },
    difficulty: 'easy',
    featured: false,
    averageRating: 4.6,
  },

  // WATER SPORTS & MARINE ACTIVITIES
  {
    id: 'exp-11',
    slug: 'diani-jet-ski-adventure',
    title: 'Jet Ski Adventure - Diani Beach',
    category: 'adventure',
    tagline: 'Ride the waves of the Indian Ocean',
    description: 'Experience the thrill of jet skiing along Diani\'s pristine coastline. No experience needed—our instructors will get you riding in minutes. Explore hidden coves, race across turquoise waters, and feel the ocean spray. Perfect for adrenaline junkies and first-timers alike.',
    duration: '1 hour',
    groupSize: { min: 1, max: 6 },
    price: 8000,
    currency: 'Ksh',
    highlights: [
      'High-speed ocean riding',
      'Safety briefing & instruction',
      'Latest model jet skis',
      'Life jackets provided',
      'Coastal exploration',
      'Photo opportunities',
    ],
    included: [
      'Jet ski rental',
      'Safety equipment',
      'Instructor guidance',
      'Fuel',
    ],
    notIncluded: [
      'Beach entry fee',
      'Photos/videos',
      'Insurance (optional)',
    ],
    location: 'Diani Beach',
    meetingPoint: 'Diani Beach Water Sports Center',
    coordinates: { lat: -4.33, lng: 39.56 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=1200',
      alt: 'Jet Skiing',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '11:00 AM', '02:00 PM', '04:00 PM'],
      seasonalAvailability: 'Best: June-March (calm seas)',
    },
    difficulty: 'easy',
    featured: true,
    averageRating: 4.9,
  },

  {
    id: 'exp-12',
    slug: 'dolphin-watching-wasini-island',
    title: 'Dolphin Watching & Wasini Island Tour',
    category: 'adventure',
    tagline: 'Swim with wild dolphins in crystal waters',
    description: 'Set sail on a traditional dhow to Wasini Island and the Kisite-Mpunguti Marine Park. Watch playful dolphins leap alongside your boat, snorkel in coral gardens teeming with tropical fish, and enjoy a fresh seafood lunch on the island. One of Kenya\'s most magical marine experiences.',
    duration: 'Full Day (7-8 hours)',
    groupSize: { min: 4, max: 12 },
    price: 11000,
    currency: 'Ksh',
    highlights: [
      'Wild dolphin encounters',
      'Snorkeling in marine park',
      'Traditional dhow sailing',
      'Fresh seafood lunch',
      'Wasini Island exploration',
      'Coral garden viewing',
    ],
    included: [
      'Dhow boat ride',
      'Park entry fees',
      'Snorkeling equipment',
      'Seafood lunch',
      'Guide',
      'Life jackets',
    ],
    notIncluded: [
      'Transport to/from Shimoni',
      'Drinks',
      'Tips for crew',
    ],
    location: 'Shimoni & Wasini Island',
    meetingPoint: 'Shimoni Jetty',
    coordinates: { lat: -4.65, lng: 39.37 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=1200',
      alt: 'Dolphins',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['07:30 AM'],
      seasonalAvailability: 'Best dolphin sightings: October-March',
    },
    difficulty: 'easy',
    featured: true,
    averageRating: 5.0,
  },

  {
    id: 'exp-13',
    slug: 'parasailing-mombasa',
    title: 'Parasailing Adventure - Mombasa',
    category: 'adventure',
    tagline: 'Soar 100 meters above the Indian Ocean',
    description: 'Experience Kenya\'s coastline from the sky! Parasailing offers breathtaking bird\'s-eye views of turquoise waters, coral reefs, and white sand beaches. Safe, thrilling, and unforgettable. No experience necessary—our certified crew handles everything.',
    duration: '30 minutes (flight time: 10-12 minutes)',
    groupSize: { min: 1, max: 8 },
    price: 7000,
    currency: 'Ksh',
    highlights: [
      'Soar 100m above ocean',
      'Panoramic coastal views',
      'Safe takeoff/landing from boat',
      'Professional crew',
      'Single or tandem flights',
      'GoPro footage available',
    ],
    included: [
      'Parasailing equipment',
      'Safety gear',
      'Boat ride',
      'Certified instructor',
    ],
    notIncluded: [
      'GoPro rental (Ksh 1,500)',
      'Photos/videos',
      'Transport',
    ],
    location: 'Mombasa North Coast',
    meetingPoint: 'Nyali Beach Water Sports',
    coordinates: { lat: -4.04, lng: 39.72 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200',
      alt: 'Parasailing',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['09:00 AM', '11:00 AM', '02:00 PM', '04:00 PM'],
      seasonalAvailability: 'Best conditions: October-March',
    },
    difficulty: 'easy',
    featured: false,
    averageRating: 4.8,
  },

  {
    id: 'exp-14',
    slug: 'scuba-diving-watamu',
    title: 'Scuba Diving Experience - Watamu',
    category: 'adventure',
    tagline: 'Discover Kenya\'s underwater paradise',
    description: 'Dive into the crystal-clear waters of Watamu Marine National Park. Whether you\'re a certified diver or trying scuba for the first time, our PADI instructors will guide you through vibrant coral reefs, schools of tropical fish, sea turtles, and possibly dolphins. Underwater visibility averages 15-20 meters.',
    duration: '3-4 hours',
    groupSize: { min: 2, max: 6 },
    price: 13500,
    currency: 'Ksh',
    highlights: [
      'PADI certified instructors',
      'Vibrant coral gardens',
      'Sea turtle encounters',
      'Tropical fish species',
      'Beginner-friendly sites',
      'Small group sizes',
    ],
    included: [
      'All diving equipment',
      'PADI instructor',
      'Boat transfer',
      'Marine park fees',
      'Drinking water',
    ],
    notIncluded: [
      'Underwater camera rental',
      'Certification courses',
      'Transport to dive center',
    ],
    location: 'Watamu Marine Park',
    meetingPoint: 'Watamu Dive Center',
    coordinates: { lat: -3.37, lng: 40.03 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?auto=format&fit=crop&w=1200',
      alt: 'Scuba Diving',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['08:00 AM', '01:00 PM'],
      seasonalAvailability: 'Best visibility: October-March',
    },
    difficulty: 'moderate',
    featured: true,
    averageRating: 4.9,
  },

  {
    id: 'exp-15',
    slug: 'kayaking-lake-naivasha',
    title: 'Kayaking with Hippos - Lake Naivasha',
    category: 'adventure',
    tagline: 'Paddle alongside hippos and eagles',
    description: 'Explore Lake Naivasha by kayak in one of Kenya\'s most unique wildlife experiences. Paddle quietly past hippos (from a safe distance!), watch African fish eagles hunt, and glide through beds of water lilies. Our guides know hippo behavior intimately, ensuring a safe yet thrilling adventure.',
    duration: '2 hours',
    groupSize: { min: 2, max: 10 },
    price: 4500,
    currency: 'Ksh',
    highlights: [
      'Hippo viewing (safe distance)',
      'Birdwatching paradise',
      'Scenic lake paddling',
      'Expert wildlife guide',
      'Water lily gardens',
      'Fish eagle sightings',
    ],
    included: [
      'Kayak rental',
      'Paddle & life jacket',
      'Wildlife guide',
      'Safety briefing',
      'Park entry',
    ],
    notIncluded: [
      'Waterproof camera',
      'Snacks/drinks',
      'Transport to lake',
    ],
    location: 'Lake Naivasha',
    meetingPoint: 'Crescent Island Jetty',
    coordinates: { lat: -0.72, lng: 36.43 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200',
      alt: 'Kayaking',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['06:30 AM', '04:00 PM'],
      seasonalAvailability: 'Best mornings: calm waters',
    },
    difficulty: 'easy',
    featured: false,
    averageRating: 4.7,
  },

  {
    id: 'exp-16',
    slug: 'deep-sea-fishing-malindi',
    title: 'Deep Sea Fishing - Malindi',
    category: 'adventure',
    tagline: 'Battle marlin and sailfish offshore',
    description: 'Head offshore in search of big game fish—marlin, sailfish, tuna, and wahoo. Malindi\'s waters are some of East Africa\'s best for sport fishing. Our experienced captains know the hotspots and provide all equipment. Catch and release or keep your trophy—your choice!',
    duration: 'Half Day (5 hours) or Full Day (8 hours)',
    groupSize: { min: 2, max: 6 },
    price: 25000,
    currency: 'Ksh',
    highlights: [
      'Big game fishing',
      'Experienced captain & crew',
      'All equipment provided',
      'Offshore adventure',
      'Marlin & sailfish season',
      'Catch & release or keep',
    ],
    included: [
      'Fishing boat charter',
      'All fishing equipment',
      'Captain & crew',
      'Fuel',
      'Drinks & snacks',
    ],
    notIncluded: [
      'Fishing license (Ksh 2,000)',
      'Lunch (full day)',
      'Transport to marina',
    ],
    location: 'Malindi',
    meetingPoint: 'Malindi Marine',
    coordinates: { lat: -3.22, lng: 40.12 },
    coverImage: {
      url: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?auto=format&fit=crop&w=1200',
      alt: 'Deep Sea Fishing',
      type: 'hero',
    },
    gallery: [],
    availability: {
      daysAvailable: [0, 1, 2, 3, 4, 5, 6],
      startTimes: ['06:00 AM'],
      seasonalAvailability: 'Best season: November-March',
    },
    difficulty: 'moderate',
    featured: false,
    averageRating: 4.8,
  },
];